version: '2'

services:

### Application Code Container

  applications:
    image: tianon/true
    volumes:
      - ${APPLICATION}${POINTER1}:/var/www${POINTER1}
      - ${APPLICATION}${POINTER2}:/var/www${POINTER2}
      - ${APPLICATION}${POINTER3}:/var/www${POINTER3}

### Workspace Utilities Container

  workspace:
    build:
      context: ./workspace
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - USER=${USER}
        - INSTALL_APC=${PHP_FPM_INSTALL_APC}
        - INSTALL_FTP=${PHP_FPM_INSTALL_FTP}
        - INSTALL_XSL=${PHP_FPM_INSTALL_XSL}
        - INSTALL_CALENDAR=${PHP_FPM_INSTALL_CALENDAR}
        - INSTALL_CTYPE=${PHP_FPM_INSTALL_CTYPE}
        - INSTALL_DBA=${PHP_FPM_INSTALL_DBA}
        - INSTALL_DOM=${PHP_FPM_INSTALL_DOM}
        - INSTALL_JSON=${PHP_FPM_INSTALL_JSON}
        - INSTALL_HASH=${PHP_FPM_INSTALL_HASH}
        - INSTALL_SOCKETS=${PHP_FPM_INSTALL_SOCKETS}
        - INSTALL_PDO=${PHP_FPM_INSTALL_PDO}
        - INSTALL_MBSTRING=${PHP_FPM_INSTALL_MBSTRING}
        - INSTALL_IMAP=${PHP_FPM_INSTALL_IMAP}
        - INSTALL_CURL=${PHP_FPM_INSTALL_CURL}
        - INSTALL_FILEINFO=${PHP_FPM_INSTALL_FILEINFO}
        - INSTALL_GETTEXT=${PHP_FPM_INSTALL_GETTEXT}
        - INSTALL_ICONV=${PHP_FPM_INSTALL_ICONV}
        - INSTALL_PHAR=${PHP_FPM_INSTALL_PHAR}
        - INSTALL_POSIX=${PHP_FPM_INSTALL_POSIX}
        - INSTALL_PSPELL=${PHP_FPM_INSTALL_PSPELL}
        - INSTALL_READLINE=${PHP_FPM_INSTALL_READLINE}
        - INSTALL_RECODE=${PHP_FPM_INSTALL_RECODE}
        - INSTALL_SHMOP=${PHP_FPM_INSTALL_SHMOP}
        - INSTALL_SIMPLEXML=${PHP_FPM_INSTALL_SIMPLEXML}
        - INSTALL_SNMP=${PHP_FPM_INSTALL_SNMP}
        - INSTALL_SYSVMSG=${PHP_FPM_INSTALL_SYSVMSG}
        - INSTALL_SYSVSEM=${PHP_FPM_INSTALL_SYSVSEM}
        - INSTALL_SYSVSHM=${PHP_FPM_INSTALL_SYSVSHM}
        - INSTALL_TIDY=${PHP_FPM_INSTALL_TIDY}
        - INSTALL_WDDX=${PHP_FPM_INSTALL_WDDX}
        - INSTALL_XML=${PHP_FPM_INSTALL_XML}
        - INSTALL_XMLREADER=${PHP_FPM_INSTALL_XMLREADER}
        - INSTALL_XMLRPC=${PHP_FPM_INSTALL_XMLRPC}
        - INSTALL_XMLWRITER=${PHP_FPM_INSTALL_XMLWRITER}
        - INSTALL_SOAP=${PHP_FPM_INSTALL_SOAP}
        - INSTALL_PGSQL=${PHP_FPM_INSTALL_PGSQL}
        - INSTALL_PG_CLIENT=${PHP_FPM_INSTALL_PG_CLIENT}
        - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
        - INSTALL_BLACKFIRE=${PHP_FPM_INSTALL_BLACKFIRE}
        - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
        - INSTALL_SWOOLE=${PHP_FPM_INSTALL_SWOOLE}
        - INSTALL_MONGO=${PHP_FPM_INSTALL_MONGO}
        - INSTALL_AMQP=${PHP_FPM_INSTALL_AMQP}
        - INSTALL_ZIP_ARCHIVE=${PHP_FPM_INSTALL_ZIP_ARCHIVE}
        - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
        - INSTALL_GMP=${PHP_FPM_INSTALL_GMP}
        - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
        - INSTALL_EXIF=${PHP_FPM_INSTALL_EXIF}
        - INSTALL_AEROSPIKE=${PHP_FPM_INSTALL_AEROSPIKE}
        - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
        - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
        - INSTALL_TOKENIZER=${PHP_FPM_INSTALL_TOKENIZER}
        - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
        - INSTALL_GHOSTSCRIPT=${PHP_FPM_INSTALL_GHOSTSCRIPT}
        - INSTALL_LDAP=${PHP_FPM_INSTALL_LDAP}
        - INSTALL_MSSQL=${PHP_FPM_INSTALL_MSSQL}
        - INSTALL_IMAGE_OPTIMIZERS=${PHP_FPM_INSTALL_IMAGE_OPTIMIZERS}
        - INSTALL_IMAGEMAGICK=${PHP_FPM_INSTALL_IMAGEMAGICK}
        - INSTALL_DRUSH=${WORKSPACE_INSTALL_DRUSH}
        - INSTALL_DRUPAL_CONSOLE=${WORKSPACE_INSTALL_DRUPAL_CONSOLE}
        - INSTALL_LARAVEL_ENVOY=${WORKSPACE_INSTALL_LARAVEL_ENVOY}
        - INSTALL_LARAVEL_INSTALLER=${WORKSPACE_INSTALL_LARAVEL_INSTALLER}
        - INSTALL_DEPLOYER=${WORKSPACE_INSTALL_DEPLOYER}
        - INSTALL_LINUXBREW=${WORKSPACE_INSTALL_LINUXBREW}
        - INSTALL_MC=${WORKSPACE_INSTALL_MC}
        - INSTALL_SYMFONY=${WORKSPACE_INSTALL_SYMFONY}
        - INSTALL_PYTHON=${WORKSPACE_INSTALL_PYTHON}
        - INSTALL_PYTHON3=${WORKSPACE_INSTALL_PYTHON3}
        - PYTHON3_VERSION=${WORKSPACE_PYTHON3_VERSION}
        - CHROME_DRIVER_VERSION=${WORKSPACE_CHROME_DRIVER_VERSION}
        - INSTALL_DUSK_DEPS=${WORKSPACE_INSTALL_DUSK_DEPS}
        - NODEJS_VERSION=${WORKSPACE_NODEJS_VERSION}
        - NODEJS_VERSION_BACKUP=${WORKSPACE_NODEJS_VERSION_BACKUP}
        # - NODEJS_YARN_VERSION=${WORKSPACE_NODEJS_YARN_VERSION}
        - NODEJS_NVM_VERSION=${WORKSPACE_NODEJS_NVM_VERSION}
        - INSTALL_WORKSPACE_SSH=${WORKSPACE_INSTALL_WORKSPACE_SSH}
      dockerfile: "Dockerfile-${PHP_VERSION}"
    volumes_from:
      - applications
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - "22:${WORKSPACE_SSH_PORT}"
    tty: true
    networks:
      - frontend
      - backend

### PHP-FPM:
  php-fpm:
    build:
      context: ./php-fpm
      args:
        - INSTALL_APC=${PHP_FPM_INSTALL_APC}
        - INSTALL_FTP=${PHP_FPM_INSTALL_FTP}
        - INSTALL_XSL=${PHP_FPM_INSTALL_XSL}
        - INSTALL_CALENDAR=${PHP_FPM_INSTALL_CALENDAR}
        - INSTALL_CTYPE=${PHP_FPM_INSTALL_CTYPE}
        - INSTALL_DBA=${PHP_FPM_INSTALL_DBA}
        - INSTALL_DOM=${PHP_FPM_INSTALL_DOM}
        - INSTALL_JSON=${PHP_FPM_INSTALL_JSON}
        - INSTALL_HASH=${PHP_FPM_INSTALL_HASH}
        - INSTALL_SOCKETS=${PHP_FPM_INSTALL_SOCKETS}
        - INSTALL_PDO=${PHP_FPM_INSTALL_PDO}
        - INSTALL_MBSTRING=${PHP_FPM_INSTALL_MBSTRING}
        - INSTALL_IMAP=${PHP_FPM_INSTALL_IMAP}
        - INSTALL_CURL=${PHP_FPM_INSTALL_CURL}
        - INSTALL_FILEINFO=${PHP_FPM_INSTALL_FILEINFO}
        - INSTALL_GETTEXT=${PHP_FPM_INSTALL_GETTEXT}
        - INSTALL_ICONV=${PHP_FPM_INSTALL_ICONV}
        - INSTALL_PHAR=${PHP_FPM_INSTALL_PHAR}
        - INSTALL_POSIX=${PHP_FPM_INSTALL_POSIX}
        - INSTALL_PSPELL=${PHP_FPM_INSTALL_PSPELL}
        - INSTALL_READLINE=${PHP_FPM_INSTALL_READLINE}
        - INSTALL_RECODE=${PHP_FPM_INSTALL_RECODE}
        - INSTALL_SHMOP=${PHP_FPM_INSTALL_SHMOP}
        - INSTALL_SIMPLEXML=${PHP_FPM_INSTALL_SIMPLEXML}
        - INSTALL_SNMP=${PHP_FPM_INSTALL_SNMP}
        - INSTALL_SYSVMSG=${PHP_FPM_INSTALL_SYSVMSG}
        - INSTALL_SYSVSEM=${PHP_FPM_INSTALL_SYSVSEM}
        - INSTALL_SYSVSHM=${PHP_FPM_INSTALL_SYSVSHM}
        - INSTALL_TIDY=${PHP_FPM_INSTALL_TIDY}
        - INSTALL_WDDX=${PHP_FPM_INSTALL_WDDX}
        - INSTALL_XML=${PHP_FPM_INSTALL_XML}
        - INSTALL_XMLREADER=${PHP_FPM_INSTALL_XMLREADER}
        - INSTALL_XMLRPC=${PHP_FPM_INSTALL_XMLRPC}
        - INSTALL_XMLWRITER=${PHP_FPM_INSTALL_XMLWRITER}
        - INSTALL_SOAP=${PHP_FPM_INSTALL_SOAP}
        - INSTALL_PGSQL=${PHP_FPM_INSTALL_PGSQL}
        - INSTALL_PG_CLIENT=${PHP_FPM_INSTALL_PG_CLIENT}
        - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
        - INSTALL_BLACKFIRE=${PHP_FPM_INSTALL_BLACKFIRE}
        - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
        - INSTALL_SWOOLE=${PHP_FPM_INSTALL_SWOOLE}
        - INSTALL_MONGO=${PHP_FPM_INSTALL_MONGO}
        - INSTALL_AMQP=${PHP_FPM_INSTALL_AMQP}
        - INSTALL_ZIP_ARCHIVE=${PHP_FPM_INSTALL_ZIP_ARCHIVE}
        - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
        - INSTALL_GMP=${PHP_FPM_INSTALL_GMP}
        - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
        - INSTALL_EXIF=${PHP_FPM_INSTALL_EXIF}
        - INSTALL_AEROSPIKE=${PHP_FPM_INSTALL_AEROSPIKE}
        - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
        - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
        - INSTALL_TOKENIZER=${PHP_FPM_INSTALL_TOKENIZER}
        - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
        - INSTALL_GHOSTSCRIPT=${PHP_FPM_INSTALL_GHOSTSCRIPT}
        - INSTALL_LDAP=${PHP_FPM_INSTALL_LDAP}
        - INSTALL_MSSQL=${PHP_FPM_INSTALL_MSSQL}
        - INSTALL_IMAGE_OPTIMIZERS=${PHP_FPM_INSTALL_IMAGE_OPTIMIZERS}
        - INSTALL_IMAGEMAGICK=${PHP_FPM_INSTALL_IMAGEMAGICK}
      dockerfile: "Dockerfile-${PHP_VERSION}"
    volumes_from:
      - applications
    volumes:
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    depends_on:
      - workspace
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    networks:
      - backend

### Networks Setup

networks: 
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

### Volumes setup

# volumes: